/* ndismod.h — NT4 Compatibility Stub
 * Auto-generated by NetCog KSM iteration
 * Part of the NT-OC AGI-OS unified build.
 */
#ifndef _NT_COMPAT_NDISMOD_H_
#define _NT_COMPAT_NDISMOD_H_
#include "ntdef.h"
#ifdef __cplusplus
extern "C" {
#endif
/* Stub — types provided by ntdef.h and subsystem-specific headers */
#ifdef __cplusplus
}
#endif
#endif /* _NT_COMPAT_NDISMOD_H_ */
