/* ntdddlc.h — NT4 Compatibility Stub
 * Auto-generated by NetCog KSM iteration
 */
#ifndef _NT_COMPAT_NTDDDLC_H_
#define _NT_COMPAT_NTDDDLC_H_
#include "ntdef.h"
#ifdef __cplusplus
extern "C" {
#endif
/* Stub — minimal definitions for NT4 source compilation */
#ifdef __cplusplus
}
#endif
#endif /* _NT_COMPAT_NTDDDLC_H_ */
